### ISSUE TITLE
panic: runtime error: index out of range when using rolling_update

### ISSUE THREAD

**Issue by wesselvdv** [eddycharly/terraform-provider-kops#352]
When using the following setttings with kOps openstack it fails:

```
  rolling_update {
    drain_and_terminate = true

    max_unavailable = "50%"
    max_surge = each.value.role == "Master" ? null : "100%"
  }

```

```
Stack trace from the terraform-provider-kops_v1.21.0-alpha.4 plugin:

panic: runtime error: index out of range [2] with length 2

goroutine 169 [running]:
k8s.io/kops/pkg/instancegroups.(*RollingUpdateCluster).rollingUpdateInstanceGroup(0xc0010b4a80, 0xc0002d3f80, 0x37e11d600, 0xb, 0xc000877108)
        k8s.io/kops@v1.21.0/pkg/instancegroups/instancegroups.go:154 +0x1454
k8s.io/kops/pkg/instancegroups.(*RollingUpdateCluster).RollingUpdate(0xc0010b4a80, 0xc000dbdbc0, 0xc00058b3b0, 0xc00058b3b0, 0xc0009eed80)
        k8s.io/kops@v1.21.0/pkg/instancegroups/rollingupdate.go:194 +0xc0c
github.com/eddycharly/terraform-provider-kops/pkg/api/utils.ClusterRollingUpdate(0x5941eb8, 0xc000f517c0, 0xc001d606f0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/eddycharly/terraform-provider-kops/pkg/api/utils/cluster_rolling_update.go:216 +0xc3d
github.com/eddycharly/terraform-provider-kops/pkg/api/resources.(*ClusterUpdater).UpdateCluster(0xc000f456b8, 0x5941eb8, 0xc000f517c0, 0x11, 0xc000f4c360)
        github.com/eddycharly/terraform-provider-kops/pkg/api/resources/ClusterUpdater.go:36 +0xff
github.com/eddycharly/terraform-provider-kops/pkg/resources.ClusterUpdaterCreateOrUpdate(0x58ee458, 0xc000fa1080, 0xc000ddea80, 0x41296e0, 0xc000f517d0, 0xc001ea57b0, 0xd0e10a, 0xc001c6ba60)
        github.com/eddycharly/terraform-provider-kops/pkg/resources/ClusterUpdater.go:26 +0xe5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0008a09a0, 0x58ee458, 0xc000fa1080, 0xc000ddea80, 0x41296e0, 0xc000f517d0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:359 +0xa7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008a09a0, 0x58ee458, 0xc000fa1080, 0xc000c490a0, 0xc001c6ba60, 0x41296e0, 0xc000f517d0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000116fa8, 0x58ee458, 0xc000fa1080, 0xc000dd6cd0, 0xc000fa1080, 0x4d021c0, 0xc000fb7e00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000839bc0, 0x58ee500, 0xc000fa1080, 0xc000c48ee0, 0xc000839bc0, 0xc000fb7ef0, 0xc000fdaba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x4d021c0, 0xc000839bc0, 0x58ee500, 0xc000fb7ef0, 0xc001c7f080, 0x0, 0x58ee500, 0xc000fb7ef0, 0xc00037b600, 0x29b)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000898540, 0x5935ff8, 0xc00038aa80, 0xc00207ad80, 0xc000aba4e0, 0x7d7d340, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000898540, 0x5935ff8, 0xc00038aa80, 0xc00207ad80, 0x0)
        google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00088c250, 0xc000898540, 0x5935ff8, 0xc00038aa80, 0xc00207ad80)
        google.golang.org/grpc@v1.37.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

Error: The terraform-provider-kops_v1.21.0-alpha.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

╷
│ Error: Plugin did not respond
│
│   with kops_cluster_updater.updater,
│   on kops.tf line 276, in resource "kops_cluster_updater" "updater":
│  276: resource "kops_cluster_updater" "updater" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

**Comment by eddycharly** [comment]
Hello @wesselvdv, thanks for reporting the issue. I'll look into it tomorrow.

**Comment by eddycharly** [comment]
@wesselvdv I can't seem to reproduce the issue with AWS, what provider version are you using ?
Given the stack trace it happens in the kOps code, it could be worth opening an issue against the kOps repository.
